import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from '../../components/Navbar';
import { ThemeChanger } from "@/utils/ThemeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DemoBLOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-amber-50 text-indigo-950 selection:bg-lime-200 dark:bg-slate-950 dark:text-amber-50 dark:selection:bg-purple-500`}>
        <ThemeChanger>
          <Navbar/>
          <main className="mx-auto max-w-5xl px-4">
            {children}
          </main>
        </ThemeChanger>
      </body>
    </html>
  );
}
